# Generated by Django 2.2.5 on 2020-03-16 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, unique=True)),
                ('test_description', models.TextField(max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=250)),
                ('test_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(max_length=100)),
                ('question_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Question')),
            ],
        ),
    ]
