# Generated by Django 2.2.5 on 2020-03-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20200316_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_answer',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
