# Generated by Django 2.2.5 on 2020-03-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_question_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=models.TextField(max_length=100),
        ),
    ]
