# Generated by Django 2.2.5 on 2020-03-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_account_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_result',
            name='result',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
