# Generated by Django 2.2.5 on 2020-03-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20200316_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
