# Generated by Django 2.2.5 on 2020-03-22 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0007_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='back.Question'),
        ),
        migrations.CreateModel(
            name='Test_timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=5)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
