# Generated by Django 2.2.5 on 2020-03-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_auto_20200323_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_timer',
            name='start_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
