# Generated by Django 2.2.5 on 2020-03-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_image',
        ),
    ]
