# Generated by Django 2.2.5 on 2020-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_delete_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
