# Generated by Django 2.2.5 on 2020-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_test_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DecimalField(decimal_places=0, default=21, max_digits=5),
            preserve_default=False,
        ),
    ]
