# Generated by Django 2.2.5 on 2020-03-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_test_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_timer',
            name='start_time',
            field=models.DecimalField(decimal_places=0, max_digits=10000000000),
        ),
    ]
