# Generated by Django 2.2.5 on 2020-03-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_auto_20200329_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_timer',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
