# Generated by Django 2.2.5 on 2020-03-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_auto_20200329_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_timer',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
