# Generated by Django 2.2.5 on 2020-03-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_auto_20200329_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
        migrations.CreateModel(
            name='RightAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Question')),
            ],
        ),
    ]
