# Generated by Django 2.2.5 on 2020-03-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_auto_20200331_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_result',
            name='result',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
