# Generated by Django 2.2.5 on 2020-04-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_auto_20200402_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_timer',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
