# Generated by Django 2.2.5 on 2020-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_auto_20200402_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_result',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='test_timer',
            name='duration',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
