# Generated by Django 2.2.5 on 2020-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0023_auto_20200402_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_result',
            name='data_stop',
            field=models.DateTimeField(),
        ),
    ]
