# Generated by Django 2.2.5 on 2020-04-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0026_auto_20200402_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='test_result',
            name='data_stop',
            field=models.DateTimeField(),
        ),
    ]
